// src/main/webapp/app/entities/fee/fee-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IFee, Fee } from 'app/shared/model/fee.model';
import { FeeService } from './fee.service';

@Component({
  selector: 'jhi-fee-update',
  templateUrl: './fee-update.component.html',
})
export class FeeUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    feeType: [null, [Validators.required]],
    percent: [null, [Validators.required]],
    percentSecure: [null, [Validators.required]],
  });

  constructor(protected feeService: FeeService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ fee }) => {
      this.updateForm(fee);
    });
  }

  updateForm(fee: IFee): void {
    this.editForm.patchValue({
      id: fee.id,
      feeType: fee.feeType,
      percent: fee.percent,
      percentSecure: fee.percentSecure,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const fee = this.createFromForm();
    if (fee.id !== undefined) {
      this.subscribeToSaveResponse(this.feeService.update(fee));
    } else {
      this.subscribeToSaveResponse(this.feeService.create(fee));
    }
  }

  private createFromForm(): IFee {
    return {
      ...new Fee(),
      id: this.editForm.get(['id'])!.value,
      feeType: this.editForm.get(['feeType'])!.value,
      percent: this.editForm.get(['percent'])!.value,
      percentSecure: this.editForm.get(['percentSecure'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IFee>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-fee-heading" jhiTranslate="btcPaymentSystemApp.fee.home.createOrEditLabel">Create or edit a Fee</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="btcPaymentSystemApp.fee.feeType" for="field_feeType" [ngbTooltip]="'btcPaymentSystemApp.fee.help.feeType' | translate">Fee Type</label>
                    <select class="form-control" name="feeType" formControlName="feeType" id="field_feeType">
                        <option value="ZERO">{{ 'btcPaymentSystemApp.FeeType.ZERO' | translate }}</option>
                        <option value="LOW">{{ 'btcPaymentSystemApp.FeeType.LOW' | translate }}</option>
                        <option value="HIGH">{{ 'btcPaymentSystemApp.FeeType.HIGH' | translate }}</option>
                    </select>
                    <div *ngIf="editForm.get('feeType')!.invalid && (editForm.get('feeType')!.dirty || editForm.get('feeType')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('feeType')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="btcPaymentSystemApp.fee.percent" for="field_percent" [ngbTooltip]="'btcPaymentSystemApp.fee.help.percent' | translate">Percent</label>
                    <input type="number" class="form-control" name="percent" id="field_percent"
                           formControlName="percent"/>
                    <div *ngIf="editForm.get('percent')!.invalid && (editForm.get('percent')!.dirty || editForm.get('percent')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('percent')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('percent')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="btcPaymentSystemApp.fee.percentSecure" for="field_percentSecure" [ngbTooltip]="'btcPaymentSystemApp.fee.help.percentSecure' | translate">Percent Secure</label>
                    <input type="number" class="form-control" name="percentSecure" id="field_percentSecure"
                           formControlName="percentSecure"/>
                    <div *ngIf="editForm.get('percentSecure')!.invalid && (editForm.get('percentSecure')!.dirty || editForm.get('percentSecure')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('percentSecure')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('percentSecure')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/fee/fee-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label, UncontrolledTooltip } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './fee.reducer';
import { IFee } from 'app/shared/model/fee.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IFeeUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const FeeUpdate = (props: IFeeUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { feeEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/fee');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...feeEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="btcPaymentSystemApp.fee.home.createOrEditLabel" data-cy="FeeCreateUpdateHeading">
            Create or edit a Fee
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : feeEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="fee-id">ID</Label>
                  <AvInput id="fee-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="feeTypeLabel" for="fee-feeType">
                  Fee Type
                </Label>
                <AvInput
                  id="fee-feeType"
                  data-cy="feeType"
                  type="select"
                  className="form-control"
                  name="feeType"
                  value={(!isNew && feeEntity.feeType) || 'ZERO'}
                >
                  <option value="ZERO">ZERO</option>
                  <option value="LOW">LOW</option>
                  <option value="HIGH">HIGH</option>
                </AvInput>
                <UncontrolledTooltip target="feeTypeLabel">Fees can be ZERO, LOW, HIGH</UncontrolledTooltip>
              </AvGroup>
              <AvGroup>
                <Label id="percentLabel" for="fee-percent">
                  Percent
                </Label>
                <AvField
                  id="fee-percent"
                  data-cy="percent"
                  type="text"
                  name="percent"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                    number: { value: true, errorMessage: 'This field should be a number.' },
                  }}
                />
                <UncontrolledTooltip target="percentLabel">Percentage for a small amount transaction</UncontrolledTooltip>
              </AvGroup>
              <AvGroup>
                <Label id="percentSecureLabel" for="fee-percentSecure">
                  Percent Secure
                </Label>
                <AvField
                  id="fee-percentSecure"
                  data-cy="percentSecure"
                  type="text"
                  name="percentSecure"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                    number: { value: true, errorMessage: 'This field should be a number.' },
                  }}
                />
                <UncontrolledTooltip target="percentSecureLabel">Percentage for a high amount transaction</UncontrolledTooltip>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/fee" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  feeEntity: storeState.fee.entity,
  loading: storeState.fee.loading,
  updating: storeState.fee.updating,
  updateSuccess: storeState.fee.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(FeeUpdate);
