// src/main/webapp/app/entities/transaction/transaction.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiParseLinks } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITransaction } from 'app/shared/model/transaction.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { TransactionService } from './transaction.service';
import { TransactionDeleteDialogComponent } from './transaction-delete-dialog.component';

@Component({
  selector: 'jhi-transaction',
  templateUrl: './transaction.component.html',
})
export class TransactionComponent implements OnInit, OnDestroy {
  transactions: ITransaction[];
  eventSubscriber?: Subscription;
  itemsPerPage: number;
  links: any;
  page: number;
  predicate: string;
  ascending: boolean;

  constructor(
    protected transactionService: TransactionService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected parseLinks: JhiParseLinks
  ) {
    this.transactions = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0,
    };
    this.predicate = 'id';
    this.ascending = true;
  }

  loadAll(): void {
    this.transactionService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe((res: HttpResponse<ITransaction[]>) => this.paginateTransactions(res.body, res.headers));
  }

  reset(): void {
    this.page = 0;
    this.transactions = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInTransactions();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ITransaction): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInTransactions(): void {
    this.eventSubscriber = this.eventManager.subscribe('transactionListModification', () => this.reset());
  }

  delete(transaction: ITransaction): void {
    const modalRef = this.modalService.open(TransactionDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.transaction = transaction;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateTransactions(data: ITransaction[] | null, headers: HttpHeaders): void {
    const headersLink = headers.get('link');
    this.links = this.parseLinks.parse(headersLink ? headersLink : '');
    if (data) {
      for (let i = 0; i < data.length; i++) {
        this.transactions.push(data[i]);
      }
    }
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="btcPaymentSystemApp.transaction.home.title">Transactions</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-transaction" [routerLink]="['/transaction/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="btcPaymentSystemApp.transaction.home.createLabel">
            Create a new Transaction
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="transactions?.length === 0">
        <span jhiTranslate="btcPaymentSystemApp.transaction.home.notFound">No transactions found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="transactions && transactions.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="initiatedAt"><span jhiTranslate="btcPaymentSystemApp.transaction.initiatedAt">Initiated At</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="transactionType"><span jhiTranslate="btcPaymentSystemApp.transaction.transactionType">Transaction Type</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="isMempool"><span jhiTranslate="btcPaymentSystemApp.transaction.isMempool">Is Mempool</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="txHash"><span jhiTranslate="btcPaymentSystemApp.transaction.txHash">Tx Hash</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="fromAddress"><span jhiTranslate="btcPaymentSystemApp.transaction.fromAddress">From Address</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="toAddress"><span jhiTranslate="btcPaymentSystemApp.transaction.toAddress">To Address</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="expectedAmount"><span jhiTranslate="btcPaymentSystemApp.transaction.expectedAmount">Expected Amount</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="amount"><span jhiTranslate="btcPaymentSystemApp.transaction.amount">Amount</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="serviceFee"><span jhiTranslate="btcPaymentSystemApp.transaction.serviceFee">Service Fee</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="btcPrice"><span jhiTranslate="btcPaymentSystemApp.transaction.btcPrice">Btc Price</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="isWithdrawed"><span jhiTranslate="btcPaymentSystemApp.transaction.isWithdrawed">Is Withdrawed</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="userId"><span jhiTranslate="btcPaymentSystemApp.transaction.user">User</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="blockId"><span jhiTranslate="btcPaymentSystemApp.transaction.block">Block</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
                <tr *ngFor="let transaction of transactions ;trackBy: trackId">
                    <td><a [routerLink]="['/transaction', transaction.id, 'view']">{{ transaction.id }}</a></td>
                    <td>{{ transaction.initiatedAt | date:'medium' }}</td>
                    <td jhiTranslate="{{ 'btcPaymentSystemApp.TransactionType.' + transaction.transactionType }}">{{ transaction.transactionType }}</td>
                    <td>{{ transaction.isMempool }}</td>
                    <td>{{ transaction.txHash }}</td>
                    <td>{{ transaction.fromAddress }}</td>
                    <td>{{ transaction.toAddress }}</td>
                    <td>{{ transaction.expectedAmount }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.serviceFee }}</td>
                    <td>{{ transaction.btcPrice }}</td>
                    <td>{{ transaction.isWithdrawed }}</td>
                    <td>
                        {{ transaction.userId }}
                    </td>
                    <td>
                        <div *ngIf="transaction.blockId">
                            <a [routerLink]="['/block', transaction.blockId , 'view']" >{{ transaction.blockId }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/transaction', transaction.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/transaction', transaction.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(transaction)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/transaction/transaction.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './transaction.reducer';
import { ITransaction } from 'app/shared/model/transaction.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface ITransactionProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Transaction = (props: ITransactionProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { transactionList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="transaction-heading" data-cy="TransactionHeading">
        Transactions
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} /> Refresh List
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create new Transaction
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {transactionList && transactionList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('initiatedAt')}>
                  Initiated At <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('transactionType')}>
                  Transaction Type <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('txHash')}>
                  Tx Hash <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('expectedAmount')}>
                  Expected Amount <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('actualAmount')}>
                  Actual Amount <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('transactionFee')}>
                  Transaction Fee <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('serviceFee')}>
                  Service Fee <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('btcEuro')}>
                  Btc Euro <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('address')}>
                  Address <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('amount')}>
                  Amount <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  User <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {transactionList.map((transaction, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${transaction.id}`} color="link" size="sm">
                      {transaction.id}
                    </Button>
                  </td>
                  <td>
                    {transaction.initiatedAt ? <TextFormat type="date" value={transaction.initiatedAt} format={APP_DATE_FORMAT} /> : null}
                  </td>
                  <td>{transaction.transactionType}</td>
                  <td>{transaction.txHash}</td>
                  <td>{transaction.expectedAmount}</td>
                  <td>{transaction.actualAmount}</td>
                  <td>{transaction.transactionFee}</td>
                  <td>{transaction.serviceFee}</td>
                  <td>{transaction.btcEuro}</td>
                  <td>{transaction.address}</td>
                  <td>{transaction.amount}</td>
                  <td>{transaction.user ? transaction.user.id : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${transaction.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${transaction.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${transaction.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Transactions found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={transactionList && transactionList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ transaction }: IRootState) => ({
  transactionList: transaction.entities,
  loading: transaction.loading,
  totalItems: transaction.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Transaction);
