// src/main/webapp/app/entities/transaction/transaction-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, UncontrolledTooltip, Row, Col } from 'reactstrap';
import { TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './transaction.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ITransactionDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const TransactionDetail = (props: ITransactionDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { transactionEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="transactionDetailsHeading">
          Transaction [<strong>{transactionEntity.id}</strong>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="initiatedAt">Initiated At</span>
            <UncontrolledTooltip target="initiatedAt">Transaction initiated at</UncontrolledTooltip>
          </dt>
          <dd>
            {transactionEntity.initiatedAt ? (
              <TextFormat value={transactionEntity.initiatedAt} type="date" format={APP_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="transactionType">Transaction Type</span>
            <UncontrolledTooltip target="transactionType">Transaction enum type</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.transactionType}</dd>
          <dt>
            <span id="txHash">Tx Hash</span>
            <UncontrolledTooltip target="txHash">Transaction hash</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.txHash}</dd>
          <dt>
            <span id="expectedAmount">Expected Amount</span>
            <UncontrolledTooltip target="expectedAmount">Expected BTC amount from the customer</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.expectedAmount}</dd>
          <dt>
            <span id="actualAmount">Actual Amount</span>
            <UncontrolledTooltip target="actualAmount">Actual BTC amount of the transaction</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.actualAmount}</dd>
          <dt>
            <span id="transactionFee">Transaction Fee</span>
            <UncontrolledTooltip target="transactionFee">BTC transaction fee</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.transactionFee}</dd>
          <dt>
            <span id="serviceFee">Service Fee</span>
            <UncontrolledTooltip target="serviceFee">Service fee</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.serviceFee}</dd>
          <dt>
            <span id="btcEuro">Btc Euro</span>
            <UncontrolledTooltip target="btcEuro">BTC/Euro price at intiation</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.btcEuro}</dd>
          <dt>
            <span id="address">Address</span>
            <UncontrolledTooltip target="address">Transaction address</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.address}</dd>
          <dt>
            <span id="amount">Amount</span>
            <UncontrolledTooltip target="amount">Euro price</UncontrolledTooltip>
          </dt>
          <dd>{transactionEntity.amount}</dd>
          <dt>User</dt>
          <dd>{transactionEntity.user ? transactionEntity.user.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/transaction" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/transaction/${transactionEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ transaction }: IRootState) => ({
  transactionEntity: transaction.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(TransactionDetail);

// src/main/webapp/app/entities/transaction/transaction-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ITransaction } from 'app/shared/model/transaction.model';

@Component({
  selector: 'jhi-transaction-detail',
  templateUrl: './transaction-detail.component.html',
})
export class TransactionDetailComponent implements OnInit {
  transaction: ITransaction | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ transaction }) => (this.transaction = transaction));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="transaction">
            <h2><span jhiTranslate="btcPaymentSystemApp.transaction.detail.title">Transaction</span> {{ transaction.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.initiatedAt" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.initiatedAt' | translate">Initiated At</span></dt>
                <dd>
                    <span>{{ transaction.initiatedAt }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.transactionType" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.transactionType' | translate">Transaction Type</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'btcPaymentSystemApp.TransactionType.' + transaction.transactionType }}">{{ transaction.transactionType }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.isMempool" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.isMempool' | translate">Is Mempool</span></dt>
                <dd>
                    <span>{{ transaction.isMempool }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.txHash" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.txHash' | translate">Tx Hash</span></dt>
                <dd>
                    <span>{{ transaction.txHash }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.fromAddress" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.fromAddress' | translate">From Address</span></dt>
                <dd>
                    <span>{{ transaction.fromAddress }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.toAddress" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.toAddress' | translate">To Address</span></dt>
                <dd>
                    <span>{{ transaction.toAddress }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.expectedAmount" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.expectedAmount' | translate">Expected Amount</span></dt>
                <dd>
                    <span>{{ transaction.expectedAmount }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.amount" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.amount' | translate">Amount</span></dt>
                <dd>
                    <span>{{ transaction.amount }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.serviceFee" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.serviceFee' | translate">Service Fee</span></dt>
                <dd>
                    <span>{{ transaction.serviceFee }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.btcPrice" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.btcPrice' | translate">Btc Price</span></dt>
                <dd>
                    <span>{{ transaction.btcPrice }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.isWithdrawed" [ngbTooltip]="'btcPaymentSystemApp.transaction.help.isWithdrawed' | translate">Is Withdrawed</span></dt>
                <dd>
                    <span>{{ transaction.isWithdrawed }}</span>
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.user">User</span></dt>
                <dd>
                    {{ transaction.userId }}
                </dd>
                <dt><span jhiTranslate="btcPaymentSystemApp.transaction.block">Block</span></dt>
                <dd>
                    <div *ngIf="transaction.blockId">
                        <a [routerLink]="['/block', transaction.blockId, 'view']">{{ transaction.blockId }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/transaction', transaction.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
